apiVersion: v1
kind: Service
metadata:
  name: multi-juicer-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN to TLS Cert from ACM>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: juice-balancer-multi-juicer
    app.kubernetes.io/name: juice-balancer
    #app: multi-juicer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000  
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
