apiVersion: v1
kind: Service
metadata:
  name: multi-juicer-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-north-1:058480393195:certificate/c5d798b5-3978-4dcd-9d4e-9f0a17cc20f0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: juice-balancer-multi-juicer
    app.kubernetes.io/name: juice-balancer
    #app: multi-juicer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000  
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
